# Generated by Django 3.0.5 on 2020-04-07 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weather',
            name='rain',
            field=models.BooleanField(default=False, verbose_name='Rain'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp_in',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temp in'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp_out',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temp out'),
        ),
        migrations.AlterField(
            model_name='weather',
            name='temp_water',
            field=models.DecimalField(decimal_places=1, max_digits=3, verbose_name='Temp water'),
        ),
    ]
