# Generated by Django 3.0.5 on 2020-04-14 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200407_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weather',
            name='rain',
            field=models.PositiveSmallIntegerField(verbose_name='Rain'),
        ),
    ]
